version: '3'
services:
  backend-jenkins-test:
    container_name: backend-jenkins-test
    restart: always
    image: backend-jenkins-test
    environment:
      - USER_MYSQL=root
      - PASSWORD_MYSQL=root
      - HOST_MYSQL=201.183.60.49:1517
      - PORT=1323
    build:
      context: .
    ports:
      - "1537:1323"
    networks:
      - backend-jenkins-test
networks:
  backend-jenkins-test:


  

    